### PR TITLE
Problem: When libevent is built by uscxml, test-gen-c doesn't wait for it being built

### PR DESCRIPTION
**Pull request by gabm**
Solution: add add_dependency..

### CODE REVIEW

**Comment by sradomski** [comment]
The dependency you gave is suboptimal, test-gen-c ought to depend on uscxml, which in turn depends on libevent and all the prereqs. I will commit that eventually.

**Comment by sradomski** [comment]
I just realized that test-gen-c will not depend on uscxml as the intention is for it to be light-weight (no complete interpreter linked). However, libevent dependency is given as per target_link_libraries in test/CMakeLists.txt:111. Can you check the dependency graph with 

    cmake --graphviz=./foo.dot

please?

**Comment by gabm** [comment]
yes it depends on libevent as wanted... But it has no *real* dependency on the build target of libevent which gets started in case libevent is not installed. So what happens is that cmake starts the download of the sources and parallel to that starts building test-gen-c. So while still building libevent, the compiling of test-gen-c fails with "cannot include <event2/event.h>". Thats because test-gen-c has no dependency on the external project "building libevent" but only on the result of that build...

**Comment by sradomski** [comment]
I see the point. Guess USCXML_PREREQS dependency is good enough then.

**Pull request merged**
